version: '3.8'

services:
  server:
    build:
      context: .
    ports:
      - "8000:8000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3 
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    restart: always
